on:
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2     
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - run: dotnet publish -o publish
    - run: zip -j -r publish.zip publish
    - run: zip -j deploy.zip publish.zip aws-manifest.json
    - uses: einaregilsson/beanstalk-deploy@v10
      with:
        aws_access_key: ${{ secrets.aws_access_key_id }}
        aws_secret_key: ${{ secrets.aws_secret_access_key }}
        application_name: aws-demo
        environment_name: aws-demo-env
        version_label: ${{ github.run_number }}
        region: us-east-2
        deployment_package: deploy.zip
