on:
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2     
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - run: dotnet publish src -o dist -c Release
    - run: zip -r ${{ format('{0}/dist/publish.zip', github.workspace) }} ${{ format('{0}/dist', github.workspace) }}
